### ISSUE TITLE
how to get the img like  ' front_example.png'

### ISSUE THREAD

**Issue by lll2000123** [dscheepens/Deep-RNN-for-extreme-wind-speed-prediction#3]
I run the code and get the ""pred_distribution_epoch100.npy"". it is only  [2 rows x 151 columns]

**Comment by dscheepens** [comment]
Hi, could you tell me which part of the code you're running exactly to obtain pred_distribution_epoch100.npy? Are you trying to reproduce front_example.png or the distributions of Figure 7?

**Comment by lll2000123** [comment]
"pngpred_distribution_epoch100.npy" comes from "main.py," which is saved in"\ saved_models_final\mae_test\", and I trying to reproduce "front_example.png".thank you

**Comment by dscheepens** [comment]
The pred_distribution_epoch100.npy aren't relevant if you want to reproduce front_example.png. This is only relevant if you want to look at the forecast distributions, as in Figure 7. In order to reproduce front_example.png, you need to train and save all of the models and then use visualisation_notebook.ipynb (last section 'example forecasts') to plot the forecasts of all of the models. I've updated main.py - if you run this now it will train and save all of the models. Hope that helps.

**Comment by lll2000123** [comment]
Hi, the module 'utils' has no attribute 'predict_batchwise_persistence',is it necessary?

**Comment by dscheepens** [comment]
Hi, sorry about this - `predict_batchwise_persistence()` was changed to `sample_dataloader()` at a later stage and apparently I forgot to change this in some of the files. I've updated `visualisation_notebook.ipynb` and `save_scores.py`. `sample_dataloader()` takes as argument only the dataloader (no model or device) and essentially just returns the inputs and targets from the dataloader as lists.
